E-Commerce Web/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using ETic.Data;
using ETic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ETic.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        
        private ApplicationDbContext _db;
        private IHostingEnvironment _he;
        public ProductController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }
        
        public IActionResult Index()
        {
            return View(_db.Products.Include(c=>c.ProductTypes).Include(f=>f.SpecialTags).ToList());
        }

        [HttpPost]
        
        public IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            if (lowAmount==null || largeAmount==null)
            {
                products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).ToList();
            }
            return View(products);
        }



        
        // get create method
        public IActionResult Create()
        {
            ViewData["ProductTypeId"] = new SelectList(_db.ProductTypes.ToList(),"Id", "ProductType");
            ViewData["SpecialTagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
            return View();
        }
        
        // post create method
        [HttpPost]
        public async Task<IActionResult> Create(Products products,IFormFile image)
        {
            if (ModelState.IsValid)
            {
                var searchProduct = _db.Products.FirstOrDefault(c => c.Name == products.Name);
                if (searchProduct != null)
                {
                    ViewBag.Message = "Bu Ürün Zaten Mevcut";
                    ViewData["ProductTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
                    ViewData["SpecialTagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
                    return View(products);
                }
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    products.Image = "Images/noimage.PNG";
                }
                _db.Products.Add(products);
                await _db.SaveChangesAsync();
                TempData["save"] = "Ürün Kayıt İşlemi Başarı İle Gerçekleşti!";
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }
        

        public ActionResult Edit(int? id)
        {
            ViewData["ProductTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["SpecialTagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Products products, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    products.Image = "Images/noimage.PNG";
                }
                _db.Products.Update(products);
                await _db.SaveChangesAsync();
                TempData["save"] = "Ürün Güncelleme İşlemi Başarı İle Gerçekleşti!";
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }


        public ActionResult Details(int? id)
        {
            ViewData["ProductTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["SpecialTagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.SpecialTags).Include(c => c.ProductTypes).Where(c => c.Id == id).FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id ==null)
            {
                return NotFound();
            }
            var product = _db.Products.FirstOrDefault(x => x.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _db.Products.Remove(product);
            await _db.SaveChangesAsync();
            TempData["save"] = "Ürün Silme İşlemi Başarı İle Gerçekleşti!";
            return RedirectToAction(nameof(Index));
        }


    }
}

E-Commerce Web/Areas/Admin/Controllers/ProductTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ETic.Data;
using ETic.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETic.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypesController : Controller
    {
        private ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.ProductTypes.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Add(productTypes);
                await _db.SaveChangesAsync();
                TempData["save"] = "Kategori Kayıt İşlemi Başarı İle Gerçekleşti!";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(productTypes);
        }



        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        /// POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                await _db.SaveChangesAsync();
                TempData["edit"] = "Kategori Güncelleme İşlemi Başarı İle Gerçekleşti!";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(productTypes);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProductTypes productTypes)
        {
            return RedirectToAction(actionName: nameof(Index));
        }



        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, ProductTypes productTypes)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != productTypes.Id)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();

            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                TempData["delete"] = "Kategori Silme İşlemi Başarı İle Gerçekleşti!";
                return RedirectToAction(actionName: nameof(Index));
            }
            return View(productTypes);
        }

        



    }
}

E-Commerce Web/Areas/Admin/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ETic.Areas.Admin.Models;
using ETic.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ETic.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        ApplicationDbContext _db; 
        public RoleController(RoleManager<IdentityRole> roleManager,ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _db = db;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            ViewBag.Roles = roles;
            return View();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            IdentityRole role = new IdentityRole();
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.msg = "Bu Yetki Zaten Mevcut!";
                ViewBag.name = name;
            }
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                TempData["save"] = "Yetki Kayıt İşlemi Başarılı!";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id ,string name)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.msg = "Bu Yetki Zaten Mevcut!";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                TempData["save"] = "Yetki Güncelleme İşlemi Başarılı!";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                TempData["delete"] = "Yetki Silme İşlemi Başarılı!";
                return RedirectToAction(nameof(Index));

            }
            return View();
        }

        public async Task<IActionResult> Assign()
        {
            ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f=>f.LockoutEnd<DateTime.Now || f.LockoutEnd==null).ToList(), "Id", "UserName");
            ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Assign(RoleUserVm roleUser)
        {
            var user = _db.ApplicationUsers.FirstOrDefault(c => c.Id == roleUser.UserId);
            var ifCheckRoleAssign =await _userManager.IsInRoleAsync(user, roleUser.RoleId);
            if (ifCheckRoleAssign)
            {
                ViewBag.msg = "Bu üye zaten bu yetkiye sahip!";
                ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
                ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
                return View(); 
            }
            
            var deleting1 =  await _userManager.RemoveFromRoleAsync(user,"User");
            var deleting2 = await _userManager.RemoveFromRoleAsync(user, "Admin");
            var role = await _userManager.AddToRoleAsync(user,roleUser.RoleId);
            if (role.Succeeded)
            {
                TempData["save"] = "Yetki başarı ile atandı!";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        public ActionResult AssignUserRole()
        {
            var result = from ur in _db.UserRoles
                         join r in _db.Roles on ur.RoleId equals r.Id
                         join a in _db.ApplicationUsers on ur.UserId equals a.Id
                         select new UserRoleMaping()
                         {
                             UserId=ur.UserId,
                             RoleId=ur.RoleId,
                             UserName=a.UserName,
                             RoleName=r.Name
                         };
            ViewBag.UserRoles = result;
            return View();
        }




    }
}

E-Commerce Web/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductTypes" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="ProductTypes" class="btn btn-success" asp-route-id="@Model">
            <i class="fas fa-list-ul"></i>
        </a>
        <a asp-action="Delete" asp-controller="ProductTypes" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>

    </div>
</td>

E-Commerce Web/Views/Shared/_ButtonSpecialTag.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="SpecialTag" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="SpecialTag" class="btn btn-success" asp-route-id="@Model">
            <i class="fas fa-list-ul"></i>
        </a>
        <a asp-action="Delete" asp-controller="SpecialTag" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>

    </div>
</td>

E-Commerce Web/Views/Shared/_Categories.cshtml
@using ETic.Models;
@model dynamic
@{
    ViewData["Title"] = "Index";
}


@foreach (var item in Model)
{
    <tr>
        <td>

            @item.ProductType
        </td>
    </tr>
}

E-Commerce Web/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using ETic.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
    {
        products = new List<Products>();
    }
    count = products.Count();

}





<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/899e6e6a0e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />

    <style>
        .error {
            color: red;
        }
    </style>
</head>
<body style="background-color:lightgrey">
    <header>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/asd.png" height="35px" /></a>
                <a class="navbar-expand text-decoration-none text-white-50" asp-area="" asp-controller="Home" asp-action="Index">KARPUZ ÇAPARİ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>



                <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">

                    <ul class="navbar-nav ">
                        @if (userRole == "Admin")
                        {

                            <li class="nav-item active">
                                <a class="nav-link " asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Kategori</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link " asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">Etiket</a>
                            </li>
                            <li class="nav-item active active">
                                <a class="nav-link " asp-area="Admin" asp-controller="Product" asp-action="Index">Ürün</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" asp-area="Customer" asp-controller="User" asp-action="listUsers">Üyeler</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" asp-area="Admin" asp-controller="Role" asp-action="Index">Yetki</a>
                            </li>
                        }

                       @await Component.InvokeAsync("CategoryMenu") 
                        <partial name="_LoginPartial" />

                        <li class="nav-item">
                            <a class="btn btn-success btn-sm ml-3 " asp-area="Customer" asp-controller="Home" asp-action="Cart">
                                <i class="fa fa-shopping-cart ml-auto"></i> Sepetim
                                <span class="badge badge-light">(@count)</span>


                            </a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ETic - Mustafa Mert KARPUZ -  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>







    @RenderSection("Scripts", required: false)



</body>
</html>

@section Scripts{

    @{ await Html.RenderPartialAsync(partialViewName: "_ValidationScriptsPartial");}


}

E-Commerce Web/Views/Shared/_LockUnlock.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="User" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="User" class="btn btn-success" asp-route-id="@Model">
            <i class="fas fa-list-ul"></i>
        </a>
        <a asp-action="Active" asp-controller="User" class="btn btn-warning" asp-route-id="@Model">
            <i class="fas fa-unlock"></i>
        </a>

    </div>
</td>

E-Commerce Web/Views/Shared/_ProductButton.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="Product" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="Product" class="btn btn-success" asp-route-id="@Model">
            <i class="fas fa-list-ul"></i>
        </a>
        <a asp-action="Delete" asp-controller="Product" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>

    </div>
</td>

E-Commerce Web/Views/Shared/_RoleButtons.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="Role" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        
        <a asp-action="Delete" asp-controller="Role" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>

    </div>
</td>

E-Commerce Web/Views/Shared/_userListButtons.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="User" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="User" class="btn btn-success" asp-route-id="@Model">
            <i class="fas fa-list-ul"></i>
        </a>
        <a asp-action="Delete" asp-controller="User" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-lock"></i>
        </a>

    </div>
</td>